### ISSUE TITLE
Interactive mode

### ISSUE THREAD

**Issue by sindresorhus** [kevva/github-search-repos#1]
Would be cool to have a interactive mode if the binary is run without arguments.

Like [`yo`](https://github.com/yeoman/yo).

Where the user can search and be able to scroll up and down to see the results and hit enter to open it.

Maybe even keyboard shortcuts to change the sorting.

**Comment by kevva** [comment]
Good idea!

**Comment by kevva** [comment]
@sindresorhus, suggestions for the shortcuts?

**Comment by sindresorhus** [comment]
Looks hot :)

Feedback:
- Make the repo name bold.
- Sorting shortcuts: `b` for best match (default), `s` for stars, `f` for forks, `u` for updated. ?
- Add a screenshot to the readme.

**Comment by kevva** [comment]
- Making the name bold will stop it from being highlighted when "hovering". I don't mind it being thin tbh.
- Sounds good. Will add!
- +1
